## Codebuch Paul Weinbrenner
Stand 09.02.2022

**Grundregeln**:
Keine Sonderzeichen, keine Leerzeichen, jede Beziehung in
maximal eine Zeile. IDs aus Edge- und Nodelist müssen identisch sein.

# Edge-Attribute

**id** to **id**
Eindeutige Codierung der Knoten die eine Beziehung haben.

**relationship**
Gibt an welche Art von Beziehung besteht. 
1 = Ministerium (auch angegliedert als Staatsekretär:in)
2 = politische Funktionen
3 = Ehrenamt
4 = Unternehmen und Aufsichtsräte
5 = Stipendien
6 = Berufstätigkeit
7 = Studienort in In- und Ausland

*Erleuteung zu Relationship*

1 = Achtung: Regierung umfasst auch Staatsekretäre und das
Bundeskanzleramt, etc. hier sollte als Knoten das entsprechende
Ministerium angegeben werden.

2 = aktuelle und ehemalige politische Funktionen in politischen
Ausschüssen, Gremien und der Partei. etc. Das können auch frühere
Stationen gewesen sein, z.B. Geschäftsführer:in einer Partei, etc.

3 = umfasst alle Mitgliedschaften in NGOs, Stiftungen, Gedenkstätten,
etc: werden im Bundestagsprofil als Körperschaften öffentlichen Rechts
bezeichnet.

4 = Beteiligung an Unternehmen durch Mandate, etwa Aufsichtsratsmandate,
Gremien, etc.

5 = erhalten Stipendien (egal wann), etwa Deutsche Studienstiftung,
Parteinahe Stiftungen, Internationale Organisationen im In- und Ausland
etc.

6 = ausgeübte Berufstätigkeiten, falls vorhanden

7 = Studien- bzw. (längere) Aufenthaltsort(e) in In- und Ausland

**year**
Bezieht sich auf das Jahr, in dem die Variable relationship
erhoben wurde

# Node-Attribute

**id**
id als Initialen Vorname Nachname erfassen, also bei Franziska Brantner z.B. "fb". Für Organisationen eine sinnvolle Abkürzung wählen. Identisch mit edgelist, aber hier nur einmalige Nennung.

**name_short** 
Nachname

**name**
voller Name

**type**
0 = Person, 
1 = Organisation/Ort/Verband etc.

**sex**
Geschlecht
1 = männlich
2 = weiblich

**birth**
Geburtsjahr

**position**
jetzige Position, z.B. Staatssekretär:in, Minister
1 = Staatssekretär
2 = Minister

**education**
höchster Bildungsabschluss
1 = Abitur
2 = Bachelor
3 = Master
4 = Doktor
5 = Professor
6 = sonstige
7 = kein höherer Bildungsabschluss

**subject**
Fachrichtung bei Studium/Promotion
1 = Wirtschaft
2 = Jura
3 = Geisteswissenschaften
4 = Naturwissenschaften
5 = Technik
6 = Handwerk
7 = Sonstiges

**party** 
Parteizugehörigkeit
1 = spd
2 = grüne
3 = fdp

**religion**
Religion
1 = christlich
2 = muslimisch
3 = jüdisch
4 = keine konfession

**kids** 
Anzahl der Kinder

**twitter**
Anzahl follower

**instagram**
Anzahl follower

-**facebook** 
Anzahl follower

**youtube** 
Anzahl Abonnenten

**parteijugend** 
Mitgliedschaft in der Parteijugend
0 = nein
1 = ja

**kreis** 
Ämter auf oder Verbandschaften auf Kreisebene
0 = nein
1 = ja

**land** 
Ämter auf oder Verbandschaften auf Landesebene
0 = nein
1 = ja

**pjführung**
Führende Position in der Parteijugend
0 = nein
1 = ja

*Fehlende Werte z.B. in der Nodelist leerlassen*
